name: Autocoder Bot

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  autocoder:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set permissions for script.sh
        run: chmod +x ./scripts/script.sh

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          ./scripts/script.sh \
            "${{ env.GITHUB_TOKEN }}" \
            "${{ env.REPOSITORY }}" \
            "${{ env.ISSUE_NUMBER }}" \
            "${{ env.OPENROUTER_API_KEY }}"

      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: .

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: List files in the artifact
        run: ls -R autocoder-artifact
